#!/bin/bash
###########################################################################
#
PACKAGE_NAME="Summary Screen"
PACKAGE_FILE=""
PACKAGE_DESC=""
SBUS="0.0"

source D-LFS.functions

Calculate_ABUT_and_ABTT  #and ABTT_long

BUILD_TIME=$[ $FINISH_TIME - $START_TIME ] #Includes any down time between
TBT=`date -ud @$BUILD_TIME +%H:%M:%S`      #packages, waiting for prompts, etc

cd $BUILD_LOGS

cat >> $BUILD_LOG << EOF
$DIVIDER
Congratulations - your LFS build is complete!
               Finish Time:   $FINISH_TIME_long
               Start  Time:   $START_TIME_long
$DIVIDER
                Total Time to build LFS = $TBT
 (includes non-building time)

Estimated SBUs = $SBUT x (1 SBU=$SBU_long) = $EBTT_long
Actual SBUs   ~= $ABUT                  = $ABTT_long

Build logs can be found in:  $BOLD_cat$BUILD_LOGS$NORMAL_cat
It may be a good idea to take a look and check for build errors, particularly
if the actual build time is significantly less than the estimated build time.
A good start is to run the following commands from the build logs directory:
  grep "Stop." *
  grep "Error " *
However, results from those commands may not be all inclusive, nor necessarily
indicative, of any actual issues.  For some additional information, read the
section "Errors (ignored)" in the README.notes file.

In any case, when ready, configure your boot manager, and reboot!
$DIVIDER
EOF


clear
cat $BUILD_LOG

### ALL DONE! ###
