#!/bin/bash
#
# The remainder of the build should be run from within the 6.64 New Chroot.
#
set -e

7/7.00_Confirm
7/7.02_General_Net_Config 
7/7.03_etc_hosts  
7/7.06_LFS_Bootscripts  
7/8.02_etc_fstab
7/8.03_Linux
7/9.99_Final_Details 
#B/B.01_dhcp       #If you uncomment any of these, also uncomment the
#B/B.02_ntfs-3g    #SBUS= line in the file.
#B/B.03_links      #
