#!/tools/bin/bash
#
# Most of chapter 6 must be run from within the chroot envinronment of 6.04.
# However, run the following three scripts from the host envinronment first:
#   6/6.00_Confirm, 6/6.02_Preparing_Virtual_FS, 6/6.04_Chroot
# Then you can run this script.
#
set -e

6/6.05_Create_Directories
6/6.06_Essential_Files
6/6.07_Linux_API_Headers
6/6.08_Man-pages
6/6.09_Glibc
6/6.10_Re-adjust_Toolchain
6/6.11_Zlib
6/6.12_File
6/6.13_Binutils
6/6.14_GMP
6/6.15_MPFR
6/6.16_MPC
6/6.17_GCC
6/6.18_Sed
6/6.19_Bzip2
6/6.20_Pkg_config
6/6.21_Ncurses
6/6.22_Util-linux
6/6.23_Psmisc
6/6.24_E2fsprogs
6/6.25_Shadow
6/6.26_Coreutils
6/6.27_Iana-Etc
6/6.28_M4
6/6.29_Bison
6/6.30_Procps
6/6.31_Grep
6/6.32_Readline
6/6.33_Bash
6/6.34_Libtool
6/6.35_GDBM
6/6.36_Inetutils
6/6.37_Perl
6/6.38_Autoconf
6/6.39_Automake
6/6.40_Diffutils
6/6.41_Gawk
6/6.42_Findutils
6/6.43_Flex
6/6.44_Gettext
6/6.45_Groff
6/6.46_Xz
#6/6.47_Grub_2   #if uncommented, also uncomment its "SBUS=" line.
6/6.48_Less
6/6.49_Gzip
6/6.50_IPRoute2
6/6.51_Kbd
6/6.52_Kmod
6/6.53_Libpipeline
6/6.54_Make
6/6.55_Man-DB
6/6.56_Patch
6/6.57_Sysklogd
6/6.58_Sysvinit
6/6.59_Tar
6/6.60_Texinfo
6/6.61_Udev
6/6.62_Vim
6/6.64_Stripping_Again
